packages:
  - 'packages/*'
  - 'packages/album-metadata-manager/frontend'
  - 'packages/album-metadata-manager/backend'
  - 'packages/singles-metadata-manager/frontend'
  - 'packages/singles-metadata-manager/backend'